// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "fpspread1.h"

/////////////////////////////////////////////////////////////////////////////
// CFpspread1

IMPLEMENT_DYNCREATE(CFpspread1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CFpspread1 properties

/////////////////////////////////////////////////////////////////////////////
// CFpspread1 operations
BEGIN_MESSAGE_MAP(CFpspread1, CWnd)
//	ON_WM_LBUTTONDOWN()
END_MESSAGE_MAP()

/**
	@brief	

	@author BHK	

	@date 2009-09-14 ¿ÀÈÄ 3:37:09	

	@param	

	@return		
*/
//void CFpspread1::OnLButtonDown(UINT nFlags, CPoint point)
//{
//	
//
//	CWnd::OnLButtonDown(nFlags, point);
//}
