//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ELOAD.rc
//
#define IDC_EDIT_AUTO_TRANSFORMER_80_TAP 1
#define IDOK3                           2
#define IDC_EDIT_AUTO_TRANSFORMER_65_TAP 2
#define IDOK2                           3
#define ID_FROM_MASTER                  3
#define IDC_EDIT_AUTO_TRANSFORMER_50_TAP 3
#define IDCANCEL2                       4
#define IDR_BUS_ENTRY                   4
#define ID_SAVE_BUTTON                  4
#define IDC_EDIT_REACTOR_50_TAP         4
#define ID_SAVE                         5
#define IDC_EDIT_REACTOR_65_TAP         5
#define IDC_EDIT_REACTOR_80_TAP         6
#define IDC_EDIT_STAR_DELTA             7
#define IDC_EDIT_DIRECT_ON_LINE         8
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_MAIN_TOOLBAR                101
#define IDR_HTML_ASSIGNLOADTOBUSDLG     108
#define IDR_HTML_LOGINDLG               109
#define IDR_HTML_EXCELCONVERSION        110
#define IDD_LOADSUMMARYVIEW             111
#define IDD_LOADSUMMARYDLG              112
#define IDD_CABLESIZINGRESULTVIEW       114
#define IDD_INITPROPERTYPAGE            115
#define IDD_VIEWREVISIONVIEW            116
#define IDR_MAINFRAME                   128
#define IDR_ELoadTYPE                   129
#define IDR_PROPERTIES                  129
#define IDR_CONTEXT_MENU                130
#define IDR_POPUP_TOOLBAR               131
#define IDI_CLASS_VIEW                  132
#define IDB_CLASS_VIEW                  135
#define IDB_RESOURCE_VIEW               136
#define IDR_POPUP_SORT                  139
#define IDB_WORKSPACE                   147
#define IDB_TOOLBAR256                  151
#define IDI_PROPERTIES_BAR              153
#define IDI_CLASS_VIEW_HC               158
#define IDB_BITMAP2                     162
#define IDR_POPUP_RESOURCE              163
#define IDR_SORT                        169
#define IDB_BITMAP1                     173
#define IDR_TOOLBAR1                    174
#define IDB_BITMAP3                     178
#define IDR_MENU_IMAGES                 181
#define IDR_CONTEXT_BUS_MENU            181
#define IDR_POPUP_RESOURCE_SUB          183
#define IDD_FILTER_LIST                 184
#define IDD_FILTER_STRING               185
#define IDR_FILTER_MENU                 187
#define IDB_BITMAP4                     188
#define IDB_FILTER                      188
#define IDI_PROPERTIES_BAR_HC           192
#define IDB_PROPERTIES_HC               196
#define IDR_MENU1                       196
#define IDR_POPUP_ITEM_LIST             196
#define IDR_CONTEXT_LOAD_MENU           196
#define IDB_CLASS_VIEW_HC               197
#define IDD_EXCEL_IMPORT_DIALOG         197
#define IDB_SORT_HC                     198
#define IDS_STRING_LOAD_TYPE            199
#define IDS_STRING_LOAD_ITEM            200
#define IDS_BUS_TYPE                    200
#define IDS_STRING_BUS_TYPE             201
#define IDD_WORK_STATUS                 202
#define IDS_NO_PROJECT_NO               202
#define IDS_EXIST_PROJECT_NO            203
#define IDS_EXIST_TABLE_NO              204
#define IDS_EXIST_TABLE_NO2             205
#define IDS_STRING_LOAD_SUMMARY_TYPE    205
#define IDB_RESOURCE_VIEW_HC            206
#define IDD_DIALOG2                     206
#define IDS_HOME                        206
#define IDR_GRID_CONTEXT_MENU           207
#define IDS_PROJECT                     207
#define IDS_LOADSUMMARY                 208
#define IDR_BUS_COPY_MENU               209
#define IDS_CABLE                       209
#define IDD_ASSIGN_LOAD_TO_BUS_DIALOG   210
#define IDD_ASSIGN_LOAD_TO_BUS          210
#define IDS_POWERCABLE                  210
#define IDB_BITMAP5                     211
#define IDB_TAB                         211
#define IDS_CONTROLCABLE                211
#define IDB_BITMAP_BOX                  212
#define IDS_TOOLS                       212
#define IDB_BITMAP6                     213
#define IDB_BITMAP_MULTI_BOXES          213
#define IDS_LIBRARY                     213
#define IDI_OK                          214
#define IDS_ADMIN                       214
#define IDB_OK                          215
#define IDS_NEW_PROJECT                 215
#define IDI_LOAD                        216
#define IDS_VIEW_REVISION               216
#define IDS_COMPARE_REVISION_DATA_TYPE  216
#define IDI_BUS                         217
#define IDS_BUS_TO_BUS                  217
#define IDS_BUS_TO_BUS_TYPE             217
#define IDI_ICON1                       218
#define IDI_BUS_GROUP                   218
#define IDD_DIALOG_LOGIN                219
#define IDI_ICON2                       221
#define IDI_CANCEL                      221
#define IDR_ADMIN_MENU                  222
#define IDD_NEW_PROJECT                 223
#define IDD_PROJECT_SETTING             225
#define IDD_LOAD_SUMMARY_SETTING        225
#define IDI_ICON3                       226
#define IDI_MOTOR                       226
#define IDB_BITMAP8                     227
#define IDD_CABLE_SIZING_PAGE           230
#define IDD_CABLE_DATA                  230
#define IDD_CABLE_SIZING_START_UP       236
#define IDR_CONTEXT_SHOWLOAD_MENU       239
#define IDR_CONTEXT_CALC_LOADSUMMARY_MENU 240
#define IDD_MULTI_SORT                  241
#define IDR_CONTEXT_CALC_CABLESIZING_MENU 241
#define IDR_CONTEXT_TRANSFORMER_MENU    242
#define IDD_LOADSUMMARYSTARTUPDLG       243
#define IDD_WORK_STATUS1                244
#define IDD_SIMPLE_PROGRESSBAR          244
#define IDI_OK_18X18                    245
#define IDI_CANCEL_18X18                246
#define IDI_ICON6                       249
#define IDI_ICON5                       252
#define IDI_EXCEL_EXPORT                253
#define IDI_EXCEL_IMPORT                254
#define IDI_EXCEL_DELETE                255
#define IDD_SIMPLE_ANIMATION            256
#define IDR_GIF1                        259
#define IDI_ASCENDING                   260
#define IDI_DESCENDING                  261
#define IDD_CONDUIT_TABLE_PAGE          262
#define IDD_CABLESIZINGVIEW             263
#define IDI_ADD                         264
#define IDI_DEL                         265
#define IDB_BITMAP9                     266
#define IDB_CHECK                       266
#define IDS_STRING_CABLE_SIZING_TYPE    269
#define IDD_SELECT_PROJECT              270
#define IDS_STRING_CABLE_SIZING_TYPE2   270
#define IDS_STRING_CABLE_SIZING_RESULT_TYPE 270
#define IDS_STRING_AUTO_POWER_CABLE_TYPE 270
#define IDD_CABLE_SIZING_SETTING        271
#define IDS_STRING_TRASNFORMER_SIZING_RESULT_TYPE 271
#define IDS_STRING_TRANSFORMER_SIZING_RESULT_TYPE 271
#define IDI_LOCK                        272
#define IDS_STRING_CABLE_ROUTE_CABLE_LIST_TYPE 272
#define IDI_ICON7                       273
#define IDI_UNLOCK                      273
#define IDS_STRING_CONTROL_CABLE_RESULT_TYPE2 273
#define IDS_STRING_CONTROL_CABLE_RESULT_TYPE 273
#define IDS_STRING_POWER_CABLE_VERIFICATION_TYPE 274
#define IDB_LOAD_SUMMARY                275
#define IDS_STRING_CONTROL_CABLE_RESULT_TYPE3 275
#define IDS_STRING_USER_CABLE_RESULT_TYPE 275
#define IDB_CABLE_SIZING                276
#define IDS_STRING_EXCEL_REPORT_FORMAT_RESULT_TYPE 276
#define IDS_STRING_CABLE_SCHEDULE_RESULT_TYPE 277
#define IDI_CABLE_SIZING                278
#define IDS_STRING_DRUM_SCHEDULE_RESULT_TYPE 278
#define IDS_STRING_LOAD_LIST_SLD_RESULT_TYPE 279
#define IDI_ICON4                       282
#define IDI_LOAD_SUMMARY                282
#define IDD_VAOLTAGE_SETTING            283
#define IDD_POWER_CABLE_CREATION        284
#define IDD_POWER_CABLE_CREATION_SETTING 284
#define IDD_POWER_CABLE_SIZING_OF_FAULT_CURRENT 285
#define IDD_POWER_CABLE_NAMING_RULE_DIALOG 286
#define IDD_TRANSFORMER_PROP            287
#define IDI_TRANSFORMER                 288
#define IDB_TRANSFORMER                 290
#define IDD_SHOW_CABLE                  291
#define IDI_ICON8                       292
#define IDI_CABLE                       292
#define IDR_CONTEXT_CREATE_CABLE_SIZING_RESULT_MENU 294
#define IDR_CONTEXT_TRANSFORMER_MENU1   295
#define IDR_CONTEXT_CABLE_MENU          295
#define IDD_TRANSFORMER_DIALOG          295
#define IDD_TRANSFORMER_SIZING_RESULT_VIEW 295
#define IDD_VIRTUAL_LOAD_SUMMARY        298
#define IDD_POWER_CABLE_CREATION_DIALOG 299
#define IDI_GRABBER                     300
#define IDD_CONTROL_TYPE_CREATION_DIALOG 301
#define IDD_SCHEMATIC_TYPE_CREATION_DIALOG 302
#define IDR_MENU2                       303
#define IDR_CONTROL_TYPE_CREATION_MENU  303
#define IDD_CONTROL_CALBLE_CREATION_SETTING_DIALOG 304
#define IDD_DIALOG1                     305
#define IDD_MCCB_SIZE_SETTING_DIALOG    305
#define IDD_CONTROL_CABLE_SPEC_CREATION 306
#define IDD_ASSIGN_SCHEMATIC_TYPE_TO_LOAD 307
#define IDS_CAPTION_BUTTON              308
#define IDB_BUTTONS                     309
#define IDS_CAPTION_BUTTON_TIP          310
#define IDB_WRITESMALL                  311
#define IDS_CAPTION_TEXT                312
#define IDB_WRITELARGE                  313
#define IDS_CAPTION_IMAGE_TIP           314
#define IDB_MAIN                        315
#define IDS_CAPTION_IMAGE_TEXT          316
#define IDB_INFO                        317
#define IDS_RIBBON_FILE                 318
#define IDB_FILESMALL                   319
#define IDS_RIBBON_NEW                  320
#define IDB_FILELARGE                   321
#define IDS_RIBBON_OPEN                 322
#define IDR_WINDOWS_MENU                323
#define IDS_RIBBON_SAVE                 324
#define IDR_THEME_MENU                  325
#define IDS_RIBBON_SAVEAS               326
#define IDR_CONTEXT_TR_SIZING_RESULT_MENU 326
#define IDS_RIBBON_PRINT                327
#define IDS_RIBBON_PRINT_LABEL          328
#define IDS_RIBBON_PRINT_QUICK          329
#define IDS_RIBBON_PRINT_PREVIEW        330
#define IDS_RIBBON_PRINT_SETUP          331
#define IDS_RIBBON_CLOSE                332
#define IDS_RIBBON_RECENT_DOCS          333
#define IDS_RIBBON_EXIT                 334
#define IDS_RIBBON_HOME                 335
#define IDS_RIBBON_CLIPBOARD            336
#define IDS_RIBBON_PASTE                337
#define IDS_RIBBON_CUT                  338
#define IDS_RIBBON_COPY                 339
#define IDS_RIBBON_SELECTALL            340
#define IDS_RIBBON_WINDOW               341
#define IDS_RIBBON_WINDOWS              342
#define IDS_RIBBON_STYLE                343
#define IDS_RIBBON_STYLE_TIP            344
#define IDS_RIBBON_STYLE_DESC           345
#define IDS_RIBBON_STATUSBAR            346
#define IDS_RIBBON_VIEW                 347
#define IDS_RIBBON_CAPTIONBAR           348
#define IDB_TOOLBARLARGE                349
#define IDB_FILE_SMALL                  350
#define IDB_FILE_LARGE                  351
#define IDB_BITMAP7                     352
#define IDB_WATERMARK                   352
#define IDB_BANNER_ICON                 353
#define IDD_WIZARD                      354
#define IDI_NEXT                        355
#define IDI_PRE                         358
#define IDI_WIZARDLARGE                 359
#define IDI_ICON9                       362
#define IDI_LEFT_ARROW                  362
#define IDD_VIEW_REVISION               363
#define IDD_SAVE_PRODUCT_TO_REVISION    364
#define IDD_CABLE_BM_SUMMARY_DIALOG     365
#define IDD_CABLE_BM_SUMMARY            365
#define IDD_CABLE_ROUTE_TYPE_CREATION_DIALOG 366
#define IDD_CABLE_ROUTE_GROUND_CREATION_DIALOG 367
#define IDD_CABLE_ROUTE_GROUP_CREATION_DIALOG 367
#define IDD_CABLE_ROUTE_ASSIGN_TO_LOAD_DIALOG 368
#define IDD_CABLE_TRAY_FILL_RATE_CALCULATION_DIALOG 369
#define IDB_MULTI_CABLE                 370
#define IDB_SINGLE_CABLE                371
#define IDD_CONTROL_CABLE_CREATION      372
#define IDI_ICON10                      374
#define IDI_REVISION                    374
#define IDD_CAPACITOR_DIALOG            375
#define IDD_CAPACITOR_PROP              375
#define IDB_CAPACITOR                   376
#define IDD_GENERATOR                   376
#define IDD_GENERATOR_PROP              376
#define IDB_GENERATOR                   377
#define IDR_MENU3                       377
#define IDR_CONTEXT_CAPACITOR_MENU      377
#define IDD_PG1                         377
#define IDR_CONTEXT_GENERATOR_MENU      378
#define IDB_PG1                         378
#define IDD_PG2                         378
#define IDB_PG3                         379
#define IDD_PG3                         379
#define IDB_PG2                         380
#define IDI_CAPACITOR                   382
#define IDI_GENERATOR                   383
#define IDD_SCHEMATIC_TYPE_INFO         384
#define IDD_CONTROLCABLE_TYPE_INFO      385
#define IDI_STRAIGHT                    386
#define IDI_RIGHT                       387
#define IDD_SHOW_REMARK                 387
#define IDI_LEFT                        388
#define IDD_PG4                         388
#define IDD_LOAD_LIST                   388
#define IDD_SCHEM_TYPE_COPY             389
#define IDB_BITMAP10                    390
#define IDB_ELOAD                       390
#define IDD_CABLEROUTECABLELISTVIEW     390
#define IDR_BUS_DIAGRAM_OPEN            391
#define IDD_UPSDC_PROP                  391
#define IDI_ICON11                      392
#define IDI_EXCEL                       392
#define IDR_CONTEXT_GENERATOR_MENU1     392
#define IDR_CONTEXT_UPSDC_MENU          392
#define IDD_CONTROL_CABLE_RESULT_VIEW   392
#define IDB_UPSDC                       394
#define IDI_ICON12                      395
#define IDI_UPSDC                       395
#define IDR_CONTEXT_SCHEMATIC_MENU      396
#define IDR_CONTEXT_CONTROLTYPE_MENU    397
#define IDI_CONTROLCABL                 399
#define IDI_CONTROLCABLE                399
#define IDD_DIALOG_SCHEMATIC_TYPE_CHECK 400
#define IDR_CONTEXT_USER_CABLE_MENU     401
#define IDD_PROJECT_INFO                401
#define IDD_USER_CABLE_RESULT_VIEW      402
#define IDR_CONTEXT_CONTROL_CABLE_RESULT_MENU1 402
#define IDR_CONTEXT_CONTROL_CABLE_RESULT_MENU 402
#define IDB_PG2_A                       403
#define IDD_CABLE_SCHEDULE_SETTING      404
#define IDD_EXCEL_REPORT_FORMAT_VIEW    405
#define IDD_EXCEL_IMPORT_DIALOG1        406
#define IDD_USER_CABLE_IMPORT           406
#define IDD_DIALOG3                     407
#define IDD_SELECT_TEMPLATE_DIALOG      407
#define IDD_TEMPLATE_MAPPING            407
#define IDD_DATA_RESULT_DIALOG          408
#define IDI_ICON13                      409
#define IDI_PDB                         409
#define IDD_DRUM_SCHEDULE_CREATION      409
#define IDD_DRUMSCHEDULERESULTVIEW      410
#define IDB_LOGO                        411
#define IDD_LOAD_LIST_SLD_VIEW          411
#define IDI_ICON14                      412
#define IDI_SAVE                        412
#define IDI_REFRESH                     413
#define IDI_SUBBUS                      415
#define IDR_MENU4                       419
#define IDR_CONTEXT_BUS_TO_BUS_MENU     419
#define IDC_MYLABEL1                    1006
#define IDC_MYTEXT1                     1007
#define IDC_MYLABEL3                    1010
#define IDC_COMBO_PROJECT               1011
#define IDC_MYLABEL2                    1014
#define IDC_EDIT_ID                     1017
#define IDC_EDIT_PASSWORD               1018
#define IDC_GRADIENTLABEL1              1020
#define IDC_MYTEXT4                     1026
#define IDC_EDIT_FOLDER                 1038
#define IDC_COMPANY_URL                 1041
#define IDC_RADIO1                      1043
#define IDC_BUSIS_EDIT                  1044
#define IDC_RADIO2                      1044
#define IDC_FILTER                      1045
#define IDC_SINGLE_RST_RADIO            1045
#define IDC_RADIO3                      1045
#define IDC_FILTER_LIST                 1046
#define IDC_CABLE_TRAY_SYSTEM_OPTION_3_RADIO 1046
#define IDC_DIR_EDIT                    1047
#define IDC_RADIO4                      1047
#define IDC_DIR_OPEN                    1048
#define IDC_RADIO5                      1048
#define IDC_ROWCOUNT_EDIT               1049
#define IDC_RADIO6                      1049
#define IDC_RADIO7                      1050
#define IDC_PROGRESS                    1051
#define IDC_RADIO8                      1051
#define IDC_EDIT_PG1                    1052
#define IDC_EDIT1                       1053
#define IDC_EDIT_NAME                   1053
#define IDC_EDIT_SELECTED_TABLE_FOR_LOAD_SUMMARY 1053
#define IDC_EDIT_BUS_MOTOR_VOLTAGE1     1053
#define IDC_CONTINUOUS                  1053
#define IDC_SELECT_PROJECT_EDIT         1053
#define IDC_CONTINUOUS_EDIT             1053
#define IDC_EDIT_3PH_MOTOR              1053
#define IDC_HV1_BUS_VOLTAGE_EDIT        1053
#define IDC_EDIT_TRANSFORMER_ID         1053
#define IDC_EDIT_LOAD_ID                1053
#define IDC_TAG_NAMING_RULE_EDIT        1053
#define IDC_EDIT_PF                     1053
#define IDC_SCHEMATIC_TYPE_EDIT         1053
#define IDC_CABLE_PREFIX_EDIT           1053
#define IDC_LV_POWERCABLE_FILL_RATE_EDIT 1053
#define IDC_EDIT_DCS_DESIGN_LENGTH      1053
#define IDC_ROUTE_TYPE_EDIT             1053
#define IDC_START_EDIT                  1053
#define IDC_CONTROLCABLETRAY_EDIT       1053
#define IDC_EDIT_PG1_WL                 1053
#define IDC_EDIT_REMARK                 1053
#define IDC_EDIT_SELECTED_PG1           1053
#define IDC_EDIT_DOC_NO                 1053
#define IDC_EDIT_SELECTED_VALUE         1053
#define IDC_BM_TOTAL_EDIT               1053
#define IDC_TOTAL_ASSIGNED_LOAD_COUNT_EDIT 1053
#define IDC_SELECT_EXCEL_FILE_NAME_EDIT 1053
#define IDC_EDIT_CAPACITOR_PF           1053
#define IDC_EDIT_UPSDC_PF               1053
#define IDC_EDIT_AREA                   1053
#define IDC_EDIT                        1053
#define IDC_UG_TEMP_EDIT                1053
#define IDC_EDIT_DESC                   1054
#define IDC_EDIT_SELECTED_TABLE_FOR_LOAD_SUMMARY2 1054
#define IDC_EDIT_TABLE_DESC             1054
#define IDC_EDIT_BUS_MOTOR_VOLTAGE2     1054
#define IDC_INTERMITTENT                1054
#define IDC_INTERMITTENT_EDIT           1054
#define IDC_EDIT_3PH_FEEDER             1054
#define IDC_EDIT_FAULT_CURRENT          1054
#define IDC_HV2_BUS_VOLTAGE_EDIT        1054
#define IDC_HV1_BUS_VOLTAGE_EDIT2       1054
#define IDC_EDIT_SF                     1054
#define IDC_EDIT16                      1054
#define IDC_SCHEMATIC_DESC_EDIT         1054
#define IDC_CABLE_PREFIX_EDIT2          1054
#define IDC_CABLE_SUFFIX_EDIT           1054
#define IDC_CONTROL_CABLE_FILL_RATE_EDIT 1054
#define IDC_ROUTE_LENGTH_EDIT           1054
#define IDC_END_EDIT                    1054
#define IDC_EDIT_PG1_L                  1054
#define IDC_EDIT_OLD_SCHEM_TYPE_NAME    1054
#define IDC_EDIT1_CAPACITOR_LENGTH      1054
#define IDC_EDIT_UPSDC_LENGTH           1054
#define IDC_EDIT_CAPACITOR_LENGTH       1054
#define IDC_AG_TEMP_EDIT                1054
#define IDC_LIST_LOAD                   1055
#define IDC_EDIT_NAME2                  1055
#define IDC_EDIT_NO                     1055
#define IDC_STANDBY                     1055
#define IDC_STANDBY_EDIT                1055
#define IDC_EDIT_1PH_FEEDER             1055
#define IDC_EDIT_BUS_MOTOR_VOLTAGE3     1055
#define IDC_EDIT_HERTZ                  1055
#define IDC_EDIT_RESULT                 1055
#define IDC_HV3_BUS_VOLTAGE_EDIT        1055
#define IDC_HV2_BUS_VOLTAGE_EDIT2       1055
#define IDC_DESIGN_LENGTH_EDIT          1055
#define IDC_TD_EDIT                     1055
#define IDC_EDIT17                      1055
#define IDC_EDIT_PG1_COS                1055
#define IDC_CABLE_SUFFIX_EDIT2          1055
#define IDC_EDIT_CABLE_DESC             1055
#define IDC_EDIT_OLD_SCHEM_TYPE_DESC    1055
#define IDC_MAX_TEMP_EDIT               1055
#define IDC_TREE_BUS_GROUP              1056
#define IDC_EDIT_DERATING_FACTOR        1056
#define IDC_EDIT_DC_FEEDER              1056
#define IDC_LV1_3PH_BUS_VOLTAGE_EDIT    1056
#define IDC_HV3_BUS_VOLTAGE_EDIT2       1056
#define IDC_CABLE_SCHEDULE_SPEC_EDIT2   1056
#define IDC_BM_TOTAL_LENGTH_EDIT        1056
#define IDC_DEFAULT_SIZE_EDIT           1056
#define IDC_AFTER_CABLE_PREFIX_EDIT     1056
#define IDC_EDIT_CLIENT                 1056
#define IDC_BUTTON_SELECT_SERVER        1057
#define IDC_EDIT_VOLTAGE_DROP1          1057
#define IDC_LV2_3PH_BUS_VOLTAGE_EDIT    1057
#define IDC_AFTER_CABLE_SUFFIX_EDIT     1057
#define IDC_EDIT_CLIENT2                1057
#define IDC_EDIT_DATE                   1057
#define IDC_STATIC_MSG                  1058
#define IDC_EDIT_VOLTAGE_DROP2          1058
#define IDC_LV11_1PH_BUS_VOLTAGE_EDIT   1058
#define IDC_DETATIL_TOTAL_LENGTH_EDIT2  1058
#define IDC_AFTER_EDIT_CABLE_DESC       1058
#define IDC_STATIC_TITLE                1059
#define IDC_EDIT_STARTING_VOLTAGE_DROP1 1059
#define IDC_DC_BUS_VOLTAGE_EDIT         1059
#define IDC_BEFORE_CABLE_TYPE_EDIT      1059
#define IDC_LIST_PROJECT                1060
#define IDC_EDIT_STARTING_VOLTAGE_DROP2 1060
#define IDC_HV1_LOAD_VOLTAGE_EDIT       1060
#define IDC_BUTTON_NEW_PROJECT          1061
#define IDC_EDIT_STARTING_POWER_FACTOR  1061
#define IDC_HV2_LOAD_VOLTAGE_EDIT       1061
#define IDC_BUTTON_DELETE_PROJECT       1062
#define IDC_CHECK_APPEND                1062
#define IDC_EDIT_INSULATION_METHOD      1062
#define IDC_EDIT_PF_FOR_FEEDER          1062
#define IDC_HV3_LOAD_VOLTAGE_EDIT       1062
#define IDC_STATIC_MAPPING              1063
#define IDC_LV1_3PH_LOAD_VOLTAGE_EDIT   1063
#define IDC_HV1_MAIN_PREFIX_EDIT2       1063
#define IDC_HV1_MAIN_PREFIX_EDIT        1063
#define IDC_LIST_TABLE_FOR_LOAD_SUMMARY 1064
#define IDC_LV2_3PH_LOAD_VOLTAGE_EDIT   1064
#define IDC_HV1_MAIN_SUFFIX_EDIT3       1064
#define IDC_HV1_MAIN_SUFFIX_EDIT        1064
#define IDC_BUTTON_DELETE_TABLE         1065
#define IDC_LV11_1PH_LOAD_VOLTAGE_EDIT  1065
#define IDC_HV2_MAIN_PREFIX_EDIT        1065
#define IDC_BUTTON_DELETE_CONDUIT_TABLE 1066
#define IDC_DC_LOAD_VOLTAGE_EDIT        1066
#define IDC_BUTTON_ADD_TABLE            1067
#define IDC_LV12_1PH_BUS_VOLTAGE_EDIT   1067
#define IDC_HV2_MAIN_SUFFIX_EDIT        1067
#define IDC_BUTTON_ADD_CONDUIT_TABLE    1068
#define IDC_LV12_1PH_LOAD_VOLTAGE_EDIT  1068
#define IDC_HV1_SPACE_HEADER_PREFIX_EDIT3 1068
#define IDC_HV1_SPACE_HEADER_SUFFIX_EDIT4 1069
#define IDC_HV1_SPACE_HEADER_SUFFIX_EDIT 1069
#define IDC_FPSPREAD1                   1070
#define IDC_FPSPREAD_LOAD_TYPE          1070
#define IDC_FPSPREAD_LOAD_SUMMARY       1070
#define IDC_HV1_MAIN_PREFIX_EDIT3       1070
#define IDC_HV3_MAIN_PREFIX_EDIT        1070
#define IDC_STATIC_PROJECT              1071
#define IDC_HV3_MAIN_SUFFIX_EDIT        1071
#define IDC_STATIC_ID                   1072
#define IDC_LV1_MAIN_PREFIX_EDIT        1072
#define IDC_STATIC_PASSWORD             1073
#define IDC_LV1_MAIN_SUFFIX_EDIT        1073
#define IDC_LV2_MAIN_PREFIX_EDIT        1074
#define IDC_COMBO_CABLE_TYPE            1075
#define IDC_LV2_MAIN_SUFFIX_EDIT        1075
#define IDC_COMBO_CABLE_TYPE2           1076
#define IDC_LV11_MAIN_PREFIX_EDIT       1076
#define IDC_BUTTON_IMPORT               1077
#define IDC_LV11_MAIN_SUFFIX_EDIT       1077
#define IDC_BUTTON2                     1078
#define IDC_COMBO_BUS_MOTOR_VOLTAGE3    1078
#define IDC_BUTTON_DELETE               1078
#define IDC_BUTTON_CALC                 1078
#define IDC_LV12_MAIN_PREFIX_EDIT       1078
#define IDC_END_BUTTON                  1078
#define IDC_REPORT_BUTTON               1078
#define IDC_BUTTON_TR_DELETE            1078
#define IDC_BUTTON_EXPORT               1079
#define IDC_EDIT_COND                   1079
#define IDC_LV12_MAIN_SUFFIX_EDIT       1079
#define IDC_BUTTON_DELETE2              1079
#define IDC_BUTTON_COPY                 1079
#define IDC_BUTTON_SELECT_COND          1080
#define IDC_DC_MAIN_PREFIX_EDIT         1080
#define IDC_FPSPREAD_COND               1081
#define IDC_DC_MAIN_SUFFIX_EDIT         1081
#define IDC_EDIT_FLC                    1082
#define IDC_HV1_SPACE_HEADER_PREFIX_EDIT 1082
#define IDC_BUTTON_SELECT_FLC           1083
#define IDC_FPSPREAD_FLC                1084
#define IDC_HV2_SPACE_HEADER_PREFIX_EDIT 1084
#define IDC_BUTTON_MULTI_SELECT_COND2   1085
#define IDC_HV2_SPACE_HEADER_SUFFIX_EDIT 1085
#define IDC_BUTTON_MULTI_SELECT_COND1   1086
#define IDC_HV3_SPACE_HEADER_PREFIX_EDIT 1086
#define IDC_BUTTON_MULTI_SELECT_COND3   1087
#define IDC_HV3_SPACE_HEADER_SUFFIX_EDIT 1087
#define IDC_BUTTON_MULTI_SELECT_SHOW    1088
#define IDC_LV1_SPACE_HEADER_PREFIX_EDIT 1088
#define IDC_LV1_SPACE_HEADER_SUFFIX_EDIT 1089
#define IDC_CONTINUOUS_SPIN             1090
#define IDC_LV2_SPACE_HEADER_PREFIX_EDIT 1090
#define IDC_INTERMITTENT_SPIN           1091
#define IDC_LV2_SPACE_HEADER_SUFFIX_EDIT 1091
#define IDC_STANDBY_SPIN                1092
#define IDC_STATIC_STANDBY              1093
#define IDC_STATIC_INTERMITTENT         1094
#define IDC_STATIC_CONTINUOUS           1095
#define IDC_MYPICTURE                   1097
#define IDC_BUTTON_MULTI_SORT_DIR1      1099
#define IDC_BUTTON_MULTI_SORT_DIR2      1100
#define IDC_COMBO_BUS                   1100
#define IDC_BUTTON_MULTI_SORT_DIR3      1101
#define IDC_COMBO_INSULATION_METHOD     1101
#define IDC_COMBO_BUS2                  1102
#define IDC_COMBO_CABLE_DATA_TABLE      1102
#define IDC_LIST_CONDUIT_TABLE          1103
#define IDC_FPSPREAD_CONDUIT_TABLE      1104
#define IDC_LIST_CABLE_DATA_TABLE       1104
#define IDC_LIST_CABLE_DATA             1106
#define IDC_FPSPREAD_CABLE_SIZING       1107
#define IDC_SELECT_PROJECT              1108
#define IDC_COMBO_MOTOR_TYPE            1111
#define IDC_STATIC_PROP                 1112
#define IDC_EDIT_DATA_NAME              1113
#define IDC_COMBO_HERTZ                 1114
#define IDC_BUTTON_3PH_MOTOR            1115
#define IDC_BUTTON_IMPORT_FROM_EXCEL    1115
#define IDC_BUTTON_3PH_FEEDER           1116
#define IDC_BUTTON_1PH_FEEDER           1117
#define IDC_BUTTON_DC_FEEDER            1118
#define IDC_3PH_MOTOR                   1119
#define IDC_3PH_FEEDER                  1120
#define IDC_1PH_FEEDER                  1121
#define IDC_DC_FEEDER                   1122
#define IDC_CHECK1                      1123
#define IDC_CHECK_APPLY_BY_AMBIENT_TEMP_FACTOR 1123
#define IDC_PDB_INCLUDE_CHECK           1123
#define IDC_CHECK_APPLY_ALL             1124
#define IDC_CHECK2                      1124
#define IDC_CHECK_APPLY_MINIMUM_LV_POWER_CABLE_SIZE 1124
#define IDC_MCCB_CHECK                  1124
#define IDC_METHOD2_CHECK               1124
#define IDC_CABLE_TRAY_SYSTEM_CHECK2    1124
#define IDC_GRID                        1125
#define IDC_CHECK3                      1125
#define IDC_CHECK_APPLY_BY_FAULT_CURRENT_AT_HV_POWER_CABLE 1125
#define IDC_METHOD3_CHECK               1125
#define IDC_CABLE_TRAY_SYSTEM_CHECK3    1125
#define IDC_RADIO_ELOAD                 1126
#define IDC_DUCT_BANK_SYSTEM_CHECK1     1126
#define IDC_RADIO_USER_DEFINED          1127
#define IDC_VOLTAGE_SETTING             1128
#define IDC_CABLE_TRAY_DUCT_FILLING_CHECK2 1128
#define IDC_CHECK_APPLY_ALL2            1128
#define IDC_CHECK_APPLY_CONNECTED_TRANSFORMER 1128
#define IDC_1_BUTTON                    1129
#define IDC_3PH_BUTTON                  1130
#define IDC_CABLE_TRAY_DUCT_FILLING_CHECK1 1130
#define IDC_1PH_BUTTON                  1131
#define IDC_DUCT_BANK_SYSTEM_CHECK2     1131
#define IDC_BUTTON5                     1132
#define IDC_1_DELETE_BUTTON             1132
#define IDC_DC_BUTTON                   1133
#define IDC_3PH_DELETE_BUTTON           1133
#define IDC_1PH_BUTTON2                 1134
#define IDC_1PH_DELETE_BUTTON           1134
#define IDC_BUTTON1                     1134
#define IDC_SETTING_SAVE                1134
#define IDC_BUTTON_SETTING_SAVE         1134
#define IDC_BUTTON_CLEAR                1134
#define IDC_BUTTON_MOVE_TO_ORIGINAL_BUS 1134
#define IDC_BUTTON_REST_MODIFIED_VALUES 1134
#define IDC_SCHEMATIC_ADD_BUTTON        1134
#define IDC_BUTTON_COMMIT_MODIFIED_VALUES 1134
#define IDC_BUTTON_LV1                  1134
#define ID_BUTTON_SAVE                  1134
#define IDC_LV_POWERCABLE_BUTTON        1134
#define IDC_ADD_BUTTON                  1134
#define IDC_START_BUTTON                1134
#define IDC_CALC_BUTTON                 1134
#define IDC_BUTTON_SAVE                 1134
#define IDC_LISTBUDDY                   1134
#define IDC_EXCEL_IMPORT_BUTTON         1134
#define IDC_REFRESH_BUTTON              1134
#define IDC_BUTTON_TR_ADD               1134
#define ID_CABLE_CREATE                 1135
#define IDC_BUTTON_CABLE_CREATION       1135
#define IDC_BUTTON3                     1135
#define IDC_BUTTON_CHANGE_TO_BUS_ASSIGNMENT 1135
#define IDC_BUTTON_CLEAR2               1135
#define IDC_BUTTON_ADD                  1135
#define IDC_SCHEMATIC_DELETE_BUTTON     1135
#define IDC_BUTTON_LV2                  1135
#define IDC_HV_POWERCABLE_BUTTON        1135
#define IDC_DELETE_BUTTON               1135
#define IDC_BUTTON_TR_SAVE              1135
#define ID_CLOSE                        1136
#define IDC_BUTTON_CLOSE                1136
#define IDC_CABLEDATA_ADD_BUTTON        1136
#define IDC_BUTTON_LV11                 1136
#define IDC_CONTROL_CABLE_BUTTON        1136
#define IDC_SCHEMATIC_MODIFY_BUTTON     1136
#define IDC_HV_VOLTAGE_STATIC           1137
#define IDC_CABLEDATA_DELETE_BUTTON     1137
#define IDC_SCHEMATIC_DELETE_BUTTON2    1137
#define IDC_BUTTON_LV12                 1137
#define IDC_CONTROLCABLE_MODIFY_BUTTON  1137
#define IDC_LV_3PH_VOLTAGE_STATIC       1138
#define IDC_HV_STATIC                   1138
#define IDC_BUTTON_DC                   1138
#define IDC_LV_1PH_VOLTAGE_STATIC       1139
#define IDC_COMBO1                      1139
#define IDC_COMBO_AG_TEMP               1139
#define IDC_COMBO_FROM_BUS_ID           1139
#define IDC_DIRECTION_COMBO             1139
#define IDC_LOAD_AREA_COMBO             1139
#define IDC_CONTORL_CABLE_COMBO         1139
#define IDC_CONTORL_CABLE_TRAY_COMBO    1139
#define IDC_COMBO_AREA                  1139
#define IDC_COMBO_OP_MODE1              1139
#define IDC_SELECT_TABLE_COMBO          1139
#define IDC_SELECT_TEMPLATE_COMBO       1139
#define IDC_COMBO_USER_CABLE_TEMPLATE   1139
#define IDC_COMBO                       1139
#define IDC_DC_VOLTAGE_STATIC           1140
#define IDC_COMBO3                      1140
#define IDC_COMBO_APPLY_MIN_LV_POWER_CABLE_SIZE 1140
#define IDC_MAINCABLE_ADD_BUTTON        1140
#define IDC_COMBO_CONNECTED_BUS_FOR_CAPACITOR_CAPACITY 1140
#define IDC_CONTROL_CABLE_COMBO         1140
#define IDC_LOAD_BUS_COMBO              1140
#define IDC_COMBO_FROM_BUS_ID2          1140
#define IDC_COMBO_FROM2_BUS_ID          1140
#define IDC_COMBO_LOAD_LIST_TEMPLATE    1140
#define IDC_EDIT2                       1141
#define IDC_EDIT_NUMBER_OF_CONDUCTORS_1 1141
#define IDC_EDIT_LTG_PF                 1141
#define IDC_EDIT_FROM_BUS_VOLT          1141
#define IDC_MAINCABLE_DELETE_BUTTON3    1141
#define IDC_MAINCABLE_DELETE_BUTTON     1141
#define IDC_COPY_SCHEMATIC_EDIT         1141
#define IDC_CONTROLCABLE_EDIT           1141
#define IDC_EDIT_V                      1141
#define IDC_COMBO8                      1141
#define IDC_COMBO_OP_MODE2              1141
#define IDC_HV_POWER_CABLE_BM_EDIT      1141
#define IDC_EDIT_START_ROW              1141
#define IDC_COMBO_CABLE_SCHEDULE_TEMPLATE 1141
#define IDC_MIN_SPARE_EDIT              1141
#define IDC_LV_3PH_STATIC               1142
#define IDC_EDIT_WELDING_PF             1142
#define IDC_EDIT5                       1142
#define IDC_EDIT_FROM_LOAD_VOLT         1142
#define IDC_HV1_CABLE_SCHEDULE_SPEC_EDIT 1142
#define IDC_MAINCABLE_DELETE_BUTTON2    1142
#define IDC_BUTTON_SAVE_CONTROL_CABLE   1142
#define IDC_EDIT_Xd1                    1142
#define IDC_CONOTROL_CABLE_BM_EDIT      1142
#define IDC_EDIT_PROJECT_NO             1142
#define IDC_SELECT_TEMPLATE_COMBO4      1142
#define IDC_COMBO_DRUM_SCHEDULE_TEMPLATE 1142
#define IDC_LV_1PH_STATIC               1143
#define IDC_EDIT_INST_PF                1143
#define IDC_EDIT6                       1143
#define IDC_HV2_CABLE_SCHEDULE_SPEC_EDIT 1143
#define IDC_EDIT_FROM_BUS_VOLT2         1143
#define IDC_EDIT_FROM2_BUS_VOLT         1143
#define IDC_LV_POWER_CABLE_BM_EDIT      1143
#define IDC_EDIT_MOTOR_ID               1143
#define IDC_EDIT_PROJECT_NAME           1143
#define IDC_EDIT_TRANSFORMER_PF         1143
#define IDC_EDIT_TOTAL_KW               1143
#define IDC_DC_STATIC                   1144
#define IDC_EDIT_OTHERS_PF              1144
#define IDC_EDIT7                       1144
#define IDC_EDIT_CONDUIT_LENGTH         1144
#define IDC_EDIT_FROM2_LOAD_VOLT        1144
#define IDC_EDIT_MOTOR_RATING_CAPACITY  1144
#define IDC_EDIT_TRANSFORMER_LENGTH     1144
#define IDC_EDIT_TOTAL_KVA              1144
#define IDC_COMBO2                      1145
#define IDC_COMBO_UG_TEMP               1145
#define IDC_EDIT_LTG_EFF                1145
#define IDC_EDIT8                       1145
#define IDC_COMBO_FROM_CABLE_VOLT       1145
#define IDC_CABLE_TYPE_COMBO            1145
#define IDC_CONTROL_CABLE_SPEC_COMBO    1145
#define IDC_EDIT_Xd2                    1145
#define IDC_TD_COMBO                    1145
#define IDC_AREA_COMBO                  1145
#define IDC_TEMPLATE_NAME_COMBO         1145
#define IDC_COMBO_CONDUIT_TYPE          1146
#define IDC_EDIT_WELDING_EFF            1146
#define IDC_EDIT9                       1146
#define IDC_COMBO_FROM_CABLE_TYPE       1146
#define IDC_CABLE_CORE_COMBO            1146
#define IDC_DEFAULT_SIZE_COMBO          1146
#define IDC_UNIT_COMBO                  1146
#define IDC_EDIT_MOTOR_LRC              1146
#define IDC_EDIT3                       1147
#define IDC_EDIT_NUMBER_OF_CONDUCTORS_2 1147
#define IDC_EDIT_INST_EFF               1147
#define IDC_EDIT10                      1147
#define IDC_COMBO_FROM_CORE             1147
#define IDC_CABLE_SIZE_COMBO            1147
#define IDC_DUCTBANKFILLRATE_PERCENTAGE_EDIT 1147
#define IDC_EDIT_COSQL                  1147
#define IDC_EDIT_MOTOR_PF               1147
#define IDC_TEMPLATE_NAME_EDIT          1147
#define IDC_EDIT4                       1148
#define IDC_EDIT_NUMBER_OF_CONDUCTORS_OVER_2 1148
#define IDC_EDIT_OTHERS_EFF             1148
#define IDC_EDIT11                      1148
#define IDC_EDIT_FROM_SPEC              1148
#define IDC_EDIT_K                      1148
#define IDC_EDIT_MOTOR_ID2              1148
#define IDC_EDIT_MOTOR_MAX_STARTING_CAPACITY 1148
#define IDC_CHECK4                      1149
#define IDC_CHECK_LOAD_POWER_CABLE_CREATION 1149
#define IDC_EDIT_COMM_PF                1149
#define IDC_EDIT12                      1149
#define IDC_EDIT_TO_SPEC                1149
#define IDC_EDIT_RATING_CAPACITY_ABOVE  1149
#define IDC_CHECK5                      1150
#define IDC_CHECK_LOAD_ALL_POWER_CABLE  1150
#define IDC_EDIT_COMM_EFF               1150
#define IDC_EDIT13                      1150
#define IDC_COMBO_TO_CABLE_VOLT         1150
#define IDC_CHECK6                      1151
#define IDC_CHECK_LOAD_UNSIZED_POWER_CABLE_ONLY 1151
#define IDC_EDIT_CONTINUOUS_KW          1151
#define IDC_EDIT14                      1151
#define IDC_COMBO_TO_CABLE_TYPE         1151
#define IDC_CHECK7                      1152
#define IDC_CHECK_EQ_BUS_POWER_CABLE_CREATION 1152
#define IDC_EDIT_INTERMITTENT_KW        1152
#define IDC_EDIT15                      1152
#define IDC_COMBO_TO_CORE               1152
#define IDC_CHECK8                      1153
#define IDC_CHECK_EQ_BUS_ALL_POWER_CABLE 1153
#define IDC_EDIT_STAND_BY_KW            1153
#define IDC_EDIT_CALCULATED_CAPACITY    1153
#define IDC_EDIT18                      1153
#define IDC_EDIT_COSQG                  1153
#define IDC_CHECK9                      1154
#define IDC_CHECK_EQ_BUS_UNSIZED_POWER_CABLE_ONLY 1154
#define IDC_EDIT_CONTINUOUS_KVAR        1154
#define IDC_EDIT_SELECTED_CAPACITY      1154
#define IDC_EDIT19                      1154
#define IDC_EDIT_SUM_KW                 1154
#define IDC_HV_LABEL_STATIC             1155
#define IDC_EDIT_INTERMITTENT_KVAR      1155
#define IDC_HV3_CABLE_SCHEDULE_SPEC_EDIT 1155
#define IDC_EDIT_TARGET_POWER_FACTOR    1155
#define IDC_EDIT20                      1155
#define IDC_EDIT_MAX_KW                 1155
#define IDC_LV_3PH_LABEL_STATIC         1156
#define IDC_EDIT_STAND_BY_KVAR          1156
#define IDC_LV1_CABLE_SCHEDULE_SPEC_EDIT 1156
#define IDC_EDIT21                      1156
#define IDC_EDIT_W0                     1156
#define IDC_EDIT_ORIGINAL_POWER_FACTOR  1156
#define IDC_LV_1PH_LABEL_STATIC         1157
#define IDC_LV2_CABLE_SCHEDULE_SPEC_EDIT 1157
#define IDC_EDIT_IMPROVED_POWER_FACTOR  1157
#define IDC_EDIT22                      1157
#define IDC_EDIT_MAX_STARTING_CAPACITY  1157
#define IDC_EDIT_ORIGINAL_POWER_FACTOR4 1157
#define IDC_EDIT_AC_RATING_KVA          1157
#define IDC_DC_LABEL_STATIC             1158
#define IDC_LV11_CABLE_SCHEDULE_SPEC_EDIT 1158
#define IDC_EDIT23                      1158
#define IDC_EDIT_COEFF                  1158
#define IDC_EDIT_ORIGINAL_POWER_FACTOR2 1158
#define IDC_EDIT_INPUT_FLC              1158
#define IDC_CHECK10                     1159
#define IDC_CHECK_CONDUIT_LENGTH_FOR_POWER_CABLE 1159
#define IDC_EDIT_INST_LF                1159
#define IDC_EDIT24                      1159
#define IDC_EDIT_PLmax                  1159
#define IDC_EDIT_ORIGINAL_POWER_FACTOR3 1159
#define IDC_EDIT_INPUT_PF               1159
#define IDC_RADIO_CU                    1160
#define IDC_LV12_CABLE_SCHEDULE_SPEC_EDIT 1160
#define IDC_EDIT_ORIGINAL_POWER_FACTOR5 1160
#define IDC_EDIT_AC_RATING_FLC          1160
#define IDC_RADIO_AL                    1161
#define IDC_DC_CABLE_SCHEDULE_SPEC_EDIT 1161
#define IDC_EDIT_ORIGINAL_POWER_FACTOR6 1161
#define IDC_EDIT_AC_RATING_PF           1161
#define IDC_RADIO_PVC                   1162
#define IDC_HV1_MOTOR_RUNNING_EDIT      1162
#define IDC_EDIT_AC_RATING_FLC2         1162
#define IDC_EDIT_DC_RATING_FLC          1162
#define IDC_RADIO_XLPE                  1163
#define IDC_HV1_MOTOR_STARTING_EDIT     1163
#define IDC_EDIT_INPUT_LOAD_VOLT        1163
#define IDC_EDIT_FAULT_CLEARING_TIME    1164
#define IDC_HV1_FEEDER_RUNNING_EDIT     1164
#define IDC_EDIT_OUTPUT_LOAD_VOLT       1164
#define IDC_EDIT_POWER_CABLE_SIZING_OF_FAULT_CURRENT 1165
#define IDC_EDIT_AC_RATING_LOAD_VOLT    1165
#define IDC_HV_LABEL_NAMING_STATIC      1166
#define IDC_HV2_MOTOR_RUNNING_EDIT      1166
#define IDC_EDIT_DC_RATING_LOAD_VOLT    1166
#define IDC_LV_3PH_LABEL_NAMING_STATIC  1167
#define IDC_HV2_MOTOR_STARTING_EDIT     1167
#define IDC_LV_1PH_LABEL_NAMING_STATIC  1168
#define IDC_HV2_FEEDER_RUNNING_EDIT     1168
#define IDC_DC_LABEL_NAMING_STATIC      1169
#define IDC_HV3_MOTOR_RUNNING_EDIT      1169
#define IDC_HV_NAMING_STATIC            1170
#define IDC_HV3_MOTOR_STARTING_EDIT     1170
#define IDC_LV_3PH_NAMING_STATIC        1171
#define IDC_HV3_FEEDER_RUNNING_EDIT     1171
#define IDC_LV_1PH_NAMING_STATIC        1172
#define IDC_LV1_MOTOR_RUNNING_EDIT      1172
#define IDC_DC_NAMING_STATIC            1173
#define IDC_LV1_MOTOR_STARTING_EDIT     1173
#define IDC_LV1_FEEDER_RUNNING_EDIT     1174
#define IDC_HV2_CABLE_VOLTAGE_COMBO     1175
#define IDC_HV3_CABLE_VOLTAGE_COMBO     1176
#define IDC_SINGLE_123_CHECK            1177
#define IDC_LV1_CABLE_VOLTAGE_COMBO     1177
#define IDC_CABLE_CORE_COMBO2           1177
#define IDC_SINGLE_ABC_CHECK            1178
#define IDC_LV2_CABLE_VOLTAGE_COMBO     1178
#define IDC_SINGLE_RST_CHECK            1179
#define IDC_LV11_CABLE_VOLTAGE_COMBO    1179
#define IDC_PARALLEL_123_CHECK          1180
#define IDC_LV12_CABLE_VOLTAGE_COMBO    1180
#define IDC_PARALLEL_ABC_CHECK          1181
#define IDC_DC_CABLE_VOLTAGE_COMBO      1181
#define IDC_STATIC_LOAD_POWER_CABLE_CREATION 1182
#define IDC_CABLE_VOLTAGE_COMBO2        1182
#define IDC_STATIC_EQ_BUS_POWER_CABLE_CREATION 1183
#define IDC_CABLE_TYPE_COMBO2           1183
#define IDC_STATIC_DERATING_FACTOR      1184
#define IDC_STATIC_CONDUIT_SIZING_SETTING 1185
#define IDC_STATIC_MIN_POWER_FACTOR     1186
#define IDC_STATIC_POWER_CABLE_CREATION 1187
#define IDC_CABLE_CORE_COMBO3           1187
#define IDC_LV2_MOTOR_RUNNING_EDIT      1188
#define IDC_SELECT_CABLE_DATA_COMBO     1189
#define IDC_SAVE_BUTTON                 1190
#define IDC_LV2_MOTOR_STARTING_EDIT     1190
#define IDC_BUTTON_RUN                  1191
#define IDC_LV2_FEEDER_RUNNING_EDIT     1191
#define IDC_LV11_FEEDER_RUNNING_EDIT    1192
#define IDC_HV1_STATIC                  1193
#define IDC_CABLE_SIZE_COMBO2           1193
#define IDC_HV2_STATIC                  1194
#define IDC_HV3_STATIC                  1195
#define IDC_LV1_3PH_STATIC              1196
#define IDC_LV2_3PH_STATIC              1197
#define IDC_LV11_1PH_STATIC             1198
#define IDC_HV1_PHASE_STATIC            1199
#define IDC_HV2_PHASE_STATIC            1200
#define IDC_HV3_PHASE_STATIC            1201
#define IDC_LV1_3PH_PHASE_STATIC        1202
#define IDC_LV2_3PH_PHASE_STATIC        1203
#define IDC_LV11_1PH_PHASE_STATIC       1204
#define IDC_DC_PHASE_STATIC             1205
#define IDC_LV12_1PH_STATIC             1206
#define IDC_RADIO_BUS_GROUP             1206
#define IDC_LV12_1PH_PHASE_STATIC2      1207
#define IDC_LV12_1PH_PHASE_STATIC       1207
#define IDC_RADIO_BUS                   1207
#define IDC_RADIO_CABLE                 1208
#define IDC_LV12_FEEDER_RUNNING_EDIT    1208
#define IDC_HV1_STATIC2                 1208
#define IDC_RADIO_BUS_DUCT              1209
#define IDC_DC_FEEDER_RUNNING_EDIT      1209
#define IDC_HV1_STATIC3                 1209
#define IDC_COMBO_TO_BUS_ID             1210
#define IDC_HV1_SF_EDIT                 1210
#define IDC_HV1_STATIC4                 1210
#define IDC_HV2_SF_EDIT                 1211
#define IDC_HV1_STATIC5                 1211
#define IDC_HV1_CABLE_TYPE_COMBO        1212
#define IDC_HV1_STATIC6                 1212
#define IDC_HV1_CABLE_CORE_COMBO        1213
#define IDC_HV1_STATIC7                 1213
#define IDC_HV2_CABLE_TYPE_COMBO        1214
#define IDC_HV1_STATIC8                 1214
#define IDC_HV2_CABLE_CORE_COMBO        1215
#define IDC_HV1_STATIC9                 1215
#define IDC_HV1_CABLE_VOLTAGE_COMBO     1216
#define IDC_HV1_STATIC10                1216
#define IDC_HV3_CABLE_TYPE_COMBO        1217
#define IDC_HV1_STATIC11                1217
#define IDC_HV3_CABLE_CORE_COMBO        1218
#define IDC_HV1_STATIC12                1218
#define IDC_LV1_CABLE_TYPE_COMBO        1219
#define IDC_HV1_STATIC13                1219
#define IDC_LV1_CABLE_CORE_COMBO        1220
#define IDC_HV1_STATIC14                1220
#define IDC_LV2_CABLE_TYPE_COMBO        1221
#define IDC_HV1_STATIC15                1221
#define IDC_LV2_CABLE_CORE_COMBO        1222
#define IDC_HV1_STATIC16                1222
#define IDC_LV11_CABLE_TYPE_COMBO       1223
#define IDC_HV1_STATIC17                1223
#define IDC_LV11_CABLE_CORE_COMBO       1224
#define IDC_LV12_CABLE_TYPE_COMBO       1225
#define IDC_LV12_CABLE_CORE_COMBO       1226
#define IDC_DC_CABLE_TYPE_COMBO         1227
#define IDC_DC_CABLE_CORE_COMBO         1228
#define IDC_HV1_APPLY_MOTOR_STARTING_CHECK 1229
#define IDC_HV2_APPLY_MOTOR_STARTING_CHECK 1230
#define IDC_HV3_APPLY_MOTOR_STARTING_CHECK 1231
#define IDC_LV1_APPLY_MOTOR_STARTING_CHECK 1232
#define IDC_LV2_APPLY_MOTOR_STARTING_CHECK 1233
#define IDC_HV1_INSTALL_METHOD_COMBO    1234
#define IDC_HV2_INSTALL_METHOD_COMBO    1235
#define IDC_HV3_INSTALL_METHOD_COMBO    1236
#define IDC_LV1_INSTALL_METHOD_COMBO    1237
#define IDC_LV2_INSTALL_METHOD_COMBO    1238
#define IDC_LV11_INSTALL_METHOD_COMBO   1239
#define IDC_LV12_INSTALL_METHOD_COMBO   1240
#define IDC_DC_INSTALL_METHOD_COMBO     1241
#define IDC_HV1_APPLY_SPACE_HEADER_CHECK 1242
#define IDC_HV2_APPLY_SPACE_HEADER_CHECK 1243
#define IDC_HV3_APPLY_SPACE_HEADER_CHECK 1244
#define IDC_LV1_APPLY_SPACE_HEADER_CHECK 1245
#define IDC_LV2_APPLY_SPACE_HEADER_CHECK 1246
#define IDC_HV3_SF_EDIT                 1247
#define IDC_LV1_SF_EDIT                 1248
#define IDC_LV2_SF_EDIT                 1249
#define IDC_LV11_SF_EDIT                1250
#define IDC_LV12_SF_EDIT                1251
#define IDC_DC_SF_EDIT                  1252
#define IDC_HV1_AMBIENT_TEMP_COMBO      1253
#define IDC_HV2_AMBIENT_TEMP_COMBO      1254
#define IDC_HV3_AMBIENT_TEMP_COMBO      1255
#define IDC_LV1_AMBIENT_TEMP_COMBO      1256
#define IDC_LV2_AMBIENT_TEMP_COMBO      1257
#define IDC_LV11_AMBIENT_TEMP_COMBO     1258
#define IDC_LV12_AMBIENT_TEMP_COMBO     1259
#define IDC_DC_AMBIENT_TEMP_COMBO       1260
#define IDC_HV1_OTHER_EDIT              1261
#define IDC_HV2_OTHER_EDIT              1262
#define IDC_HV3_OTHER_EDIT              1263
#define IDC_LV1_OTHER_EDIT              1264
#define IDC_LV2_OTHER_EDIT              1265
#define IDC_LV11_OTHER_EDIT             1266
#define IDC_LV12_OTHER_EDIT             1267
#define IDC_DC_OTHER_EDIT               1268
#define IDC_VOLTAGE_SETTING_TITLE_STATIC 1277
#define IDC_CABLE_SETTING_TITLE_STATIC  1278
#define IDC_VOLTAGE_DROP_TITLE_STATIC   1279
#define IDC_DERATING_FACTOR_TITLE_STATIC 1280
#define IDC_LV11_APPLY_SPACE_HEADER_CHECK 1281
#define IDC_LV12_APPLY_SPACE_HEADER_CHECK 1282
#define IDC_DC_APPLY_SPACE_HEADER_CHECK 1283
#define IDC_LV1_BUS_VOLTAGE_EDIT        1284
#define IDC_LV2_BUS_VOLTAGE_EDIT        1285
#define IDC_LV11_BUS_VOLTAGE_EDIT       1286
#define IDC_LV12_BUS_VOLTAGE_EDIT       1287
#define IDC_LV1_LOAD_VOLTAGE_EDIT       1288
#define IDC_LV2_LOAD_VOLTAGE_EDIT       1289
#define IDC_LV11_LOAD_VOLTAGE_EDIT      1290
#define IDC_LV12_LOAD_VOLTAGE_EDIT      1291
#define IDC_HV1_TOTAL_EDIT              1292
#define IDC_HV2_TOTAL_EDIT              1293
#define IDC_HV3_TOTAL_EDIT              1294
#define IDC_LV1_TOTAL_EDIT              1295
#define IDC_LV2_TOTAL_EDIT              1296
#define IDC_LV11_TOTAL_EDIT             1297
#define IDC_LV12_TOTAL_EDIT             1298
#define IDC_DC_TOTAL_EDIT               1299
#define IDC_LV1_VOLTAGE_TYPE_STATIC     1300
#define IDC_LV2_VOLTAGE_TYPE_STATIC     1301
#define IDC_LV11_VOLTAGE_TYPE_STATIC    1302
#define IDC_LV12_STATIC                 1303
#define IDC_LV12_VOLTAGE_TYPE_STATIC    1303
#define IDC_HV1_VOLTAGE_TYPE_STATIC     1304
#define IDC_HV2_VOLTAGE_TYPE_STATIC     1305
#define IDC_HV3_VOLTAGE_TYPE_STATIC     1306
#define IDC_DC_VOLTAGE_TYPE_STATIC      1307
#define IDC_EDIT_LTG_LF                 1308
#define IDC_EDIT_WELDING_LF             1309
#define IDC_EDIT_COMM_LF                1310
#define IDC_EDIT_OTHERS_EFF2            1311
#define IDC_EDIT_OTHERS_LF              1312
#define IDC_HV1_AMBIENT_TEMP_EDIT       1313
#define IDC_HV2_AMBIENT_TEMP_EDIT       1314
#define IDC_HV3_AMBIENT_TEMP_EDIT       1315
#define IDC_LV1_AMBIENT_TEMP_EDIT       1316
#define IDC_LV2_AMBIENT_TEMP_EDIT       1317
#define IDC_LV11_AMBIENT_TEMP_EDIT      1318
#define IDC_LV12_AMBIENT_TEMP_EDIT      1319
#define IDC_DC_AMBIENT_TEMP_EDIT        1320
#define IDC_STATIC_CABLE_CREATION_SETTING 1321
#define IDC_STATIC_NAMING_RULE_SETTING  1322
#define IDC_STATIC_SPACE_HEADER_CABLE_SETTING 1323
#define IDC_STATIC_SINGLE_CORE_NUMBERING 1324
#define IDC_STATIC_PARALLER_CABLE_NUMBERING 1325
#define IDC_HV1_MAIN_EX_STATIC          1326
#define IDC_HV2_MAIN_EX_STATIC          1327
#define IDC_HV3_MAIN_EX_STATIC          1328
#define IDC_LV1_MAIN_EX_STATIC          1329
#define IDC_LV2_MAIN_EX_STATIC          1330
#define IDC_LV11_MAIN_EX_STATIC         1331
#define IDC_LV12_MAIN_EX_STATIC         1332
#define IDC_DC_EX_STATIC                1333
#define IDC_DC_MAIN_EX_STATIC           1334
#define IDC_HV1_SPACE_HEADER_EX_STATIC  1335
#define IDC_HV2_SPACE_HEADER_EX_STATIC  1336
#define IDC_HV3_SPACE_HEADER_EX_STATIC  1337
#define IDC_LV1_SPACE_HEADER_EX_STATIC  1338
#define IDC_LV2_SPACE_HEADER_EX_STATIC  1339
#define IDC_LIST_CABLE                  1340
#define IDC_STATIC_PROPERTY             1341
#define IDC_TREE_CABLE                  1342
#define IDC_SINGLE_123_RADIO            1343
#define IDC_SINGLE_ABC_RADIO            1344
#define IDC_PARALLEL_123_RADIO          1345
#define IDC_PARALLEL_ABC_RADIO2         1346
#define IDC_PARALLEL_ABC_RADIO          1347
#define IDC_LIST_CALCULATED_RESULT      1348
#define IDC_STATIC_CALCULATED_RESULT    1349
#define IDC_STATIC_CABLE_LIST           1350
#define IDC_STATIC_CABLE_PROPERTY       1351
#define IDC_FPSPREAD_CABLESIZING_RESULT_VIEW 1352
#define IDC_RADIO_LOAD_ALL_POWER_CABLE  1353
#define IDC_RADIO_LOAD_UNSIZED_POWER_CABLE_ONLY 1354
#define IDC_FPSPREAD_TRANSFORMER_RESULT_VIEW 1354
#define IDC_RADIO_BUS_ALL_POWER_CABLE   1355
#define IDC_RADIO_LOAD_UNSIZED_POWER_CABLE_ONLY2 1356
#define IDC_RADIO_BUS_UNSIZED_POWER_CABLE_ONLY 1356
#define IDC_STATIC_1                    1357
#define IDC_TEMPLATE_NAME_STATIC_1      1357
#define IDC_TEMPLATE_NAME_STATIC        1357
#define IDC_LIST_BUS                    1358
#define IDC_LIST3                       1360
#define IDC_LIST_TRANSFORMER            1360
#define IDC_LOAD_LIST                   1360
#define IDC_ASSIGN_LOAD_LIST            1360
#define IDC_STATIC_BUS                  1361
#define ID_POWER_CABLE_CREATION         1362
#define IDC_STATIC_TRANSFORMER_CAPACITY 1363
#define IDC_STATIC_VIRTUAL_LOAD_ASSIGNMENT 1364
#define IDC_STATIC_MOVE_TO_ORIGINAL_BUS 1365
#define IDC_STATIC_CHANGE_TO_BUS_ASSIGNMENT 1366
#define IDC_TAB1                        1367
#define IDC_LOADSUMMARY_STARTUP_TAB     1367
#define IDC_GRID_STATIC                 1368
#define ID_SETTING_SAVE                 1369
#define IDC_LIST_NOT_ASSIGNED_LOAD      1370
#define ID_SETTING_SAVE2                1370
#define IDC_BUTTON_CHECK                1370
#define IDC_STATIC_NOT_ASSIGNED         1371
#define IDC_STATIC_REST_MODIFIED_VALUES 1372
#define IDC_STATIC_COMMIT_MODIFIED_VALUES 1372
#define IDC_STATIC_NOT_ASSIGNED2        1372
#define IDC_MAIN_SCHEMATIC_STATIC       1373
#define IDC_SUB_SCHEMATIC_STATIC        1374
#define IDC_STATIC_TAB_CTRL             1378
#define ID_ADD_BUTTON                   1379
#define ID_REFRESH_BUTTON               1380
#define IDC_MCCB_SIZE_SETTING_STATIC    1381
#define IDC_MCCB_SIZE_SETTING_CHECK     1382
#define ID_APPLY_SAVE                   1383
#define IDC_APPLY_BUS_STATIC            1384
#define ID_APPLY_SAVE2                  1384
#define IDC_BUTTON_APPLY                1384
#define IDC_APPLY_PDB_STATIC            1385
#define ID_CANCEL                       1386
#define IDC_FLC_FACTOR_CHECK            1387
#define IDC_RADIO_FLC_FACTOR            1388
#define IDC_RADIO_FLC_FACTOR2           1389
#define IDC_RADIO_MCCB                  1389
#define IDC_STATIC_VERSION              1389
#define IDC_CABLE_STATIC                1390
#define IDC_CONTROL_CABLE_SETTING_STATIC 1391
#define IDC_LCS_BUTTON                  1392
#define IDC_LCP_BUTTON                  1393
#define IDC_STATIC_HV1_POWER_CABLE_LOAD_ID 1393
#define IDC_BUTTON7                     1394
#define IDC_DCS_BUTTON                  1394
#define IDC_STATIC_HV1_SPACE_HEATER_LOAD_ID 1394
#define IDC_STATIC_HV2_POWER_CABLE_LOAD_ID 1395
#define IDC_STATIC_HV2_SPACE_HEATER_LOAD_ID 1396
#define IDC_STATIC_HV3_POWER_CABLE_LOAD_ID 1397
#define IDC_STATIC_HV3_SPACE_HEATER_LOAD_ID 1398
#define IDC_STATIC_LV1_POWER_CABLE_LOAD_ID 1399
#define IDC_STATIC_LV1_SPACE_HEATER_LOAD_ID 1400
#define IDC_STATIC_LV2_POWER_CABLE_LOAD_ID 1401
#define IDC_STATIC_LV2_SPACE_HEATER_LOAD_ID 1402
#define IDC_STATIC_LV11_POWER_CABLE_LOAD_ID 1403
#define IDC_STATIC_LV12_POWER_CABLE_LOAD_ID 1404
#define IDC_STATIC_DC_POWER_CABLE_ID    1405
#define IDC_STATIC_DC_POWER_CABLE_LOAD_ID 1405
#define IDC_STATIC_LV1_BUS_VOLT         1406
#define IDC_STATIC_LV2_BUS_VOLT         1407
#define IDC_STATIC_LV11_BUS_VOLT        1408
#define IDC_STATIC_LV12_BUS_VOLT        1409
#define IDC_STATIC_DC_BUS_VOLT          1410
#define IDC_STATIC_LV1_LOAD_VOLT        1411
#define IDC_STATIC_ASSIGN_SCHEMATIC_TO_LOAD 1411
#define IDC_STATIC_LV2_LOAD_VOLT        1412
#define IDC_LIST_SCHEMATIC_TYPE         1412
#define IDC_STATIC_LV11_LOAD_VOLT       1413
#define IDC_STATIC_MOVE_TO_ORIGINAL_SCHEMATIC_TYPE 1413
#define IDC_STATIC_LV12_LOAD_VOLT       1414
#define IDC_BUTTON_MOVE_TO_ORIGINAL_SCHEMATIC_TYPE 1414
#define IDC_STATIC_DC_LOAD_VOLT         1415
#define IDC_STATIC_FRAME                1415
#define IDC_STATIC_MOVE_TO_ORIGINAL_SCHEMATIC_TYPE2 1415
#define IDC_HELP_STATIC                 1416
#define IDC_CONTROL_TYPE_LIST           1418
#define IDC_CABLE_DATA_LIST             1419
#define IDC_CONTROL_TYPE_LIST2          1419
#define IDC_CONTROL_TYPE_LIST4          1420
#define IDC_LIST_REVISION               1421
#define IDC_CONTROL_TYPE_LIST3          1421
#define IDC_LIST_LEFT_REVISION          1422
#define IDC_LIST_LEFT_PRODUCT           1422
#define IDC_LIST4                       1423
#define IDC_LIST_RIGHT_REVISION         1423
#define IDC_LIST_RIGHT_PRODUCT          1423
#define IDC_CABLE_BM_SUMMARY_STATIC     1423
#define IDC_CABLE_BM_DETAIL_STATIC      1424
#define IDC_DETAIL_TOTAL_STATIC         1430
#define IDC_LIST_STATIC                 1431
#define IDC_ROUTE_GR_DESC_EDIT          1432
#define IDC_AREA_STATIC2                1432
#define IDC_ROUTE_GR_EDIT               1433
#define IDC_UNIT_STATIC2                1433
#define IDC_MAIN_ROUTE_STATIC           1434
#define IDC_ROUTE_TYPE_LIST             1435
#define IDC_ROUTE_GR_DELETE_BUTTON      1436
#define IDC_ROUTE_GR_ADD_BUTTON         1437
#define IDC_ROUTE_GROUND_LIST           1438
#define IDC_ROUTE_GROUP_LIST            1438
#define IDC_BUS_LIST                    1439
#define IDC_NOT_ASSIGN_LIST             1439
#define IDC_IMAGE_STATIC                1440
#define IDC_METHOD1_CHECK               1441
#define IDC_IMAGE1_STATIC               1442
#define IDC_IMAGE2_STATIC               1442
#define IDC_IMAGE3_STATIC               1443
#define IDC_ROUTE_TYPE_TREE             1444
#define IDC_FPSPREAD_REVISION           1445
#define IDC_ROUTE_GROUP_TREE            1447
#define IDC_CABLE_TRAY_SYSTEM_CHECK1    1448
#define IDC_CABLETRAYSYSTEM_STATIC      1449
#define IDC_DUCTBANKSYSTEM_STATIC       1450
#define IDC_CABLETRAY_DUCTFILLING_STATIC 1451
#define IDC_DUCT_BANK_SYSTEM_OPTION_1_RADIO 1452
#define IDC_DUCT_BANK_SYSTEM_OPTION_2_RADIO 1453
#define IDC_CABLETRAY_DUCTFILLING_OPTION_1_RADIO 1454
#define IDC_CABLETRAY_DUCTFILLING_OPTION_2_RADIO 1455
#define IDC_CABLE_TRAY_SYSTEM_OPTION_1_RADIO 1456
#define IDC_CABLE_TRAY_SYSTEM_OPTION_2_RADIO 1457
#define IDC_EDIT_CAPACITOR_ID           1458
#define IDC_EDIT_GENERATOR_ID           1459
#define ID_EDIT_PG1                     1460
#define IDC_EDIT_PG3                    1461
#define IDC_EDIT_PG2                    1462
#define IDC_BUS_NAME_STATIC             1463
#define IDC_EDIT__SELECTED_PG2          1463
#define IDC_EDIT_SELECTED_PG2           1463
#define IDC_OLD_SCHEMATIC_TYPE_EDIT     1464
#define IDC_EDIT_SELECTED_PG3           1464
#define IDC_OLD_SCHEMATIC_DESC_EDIT     1465
#define IDC_BEFORE_CABLE_PREFIX_EDIT    1466
#define IDC_BEFORE_CABLE_SUFFIX_EDIT    1467
#define IDC_BEFORE_EDIT_CABLE_DESC      1468
#define IDC_AFTER_CONTROL_CABLE_SPEC_COMBO 1469
#define IDC_ROUTE_TYPE_STATIC           1470
#define IDC_ROUTE_GROUP_STATIC          1471
#define IDC_EDIT_QLMAX                  1472
#define IDC_LIST1                       1473
#define IDC_LIST_CONNECTED_LIST         1473
#define IDC_CHECK_LIST                  1473
#define IDC_LIST_REMARK                 1478
#define IDC_EDIT_NEW_SCHEM_TYPE_NAME    1479
#define IDC_FPSPREAD_CABLEROUTE_CABLE_LIST_VIEW 1480
#define IDC_EDIT_NEW_SCHEM_TYPE_DESC    1480
#define IDC_RADIO_NEW_LOADS             1481
#define IDC_RADIO_UPDATE_LOADS          1482
#define IDC_COMBO4                      1482
#define IDC_COMBO_INPUT_LOAD_VOLT       1482
#define IDC_COMBO5                      1483
#define IDC_COMBO_OUTPUT_LOAD_VOLT      1483
#define IDC_COMBO6                      1484
#define IDC_COMBO_AC_RATING_LOAD_VOLT   1484
#define IDC_COMBO7                      1485
#define IDC_COMBO_DC_RATING_LOAD_VOLT   1485
#define IDC_EDIT_UPSDC_ID               1486
#define IDC_COMBO_FROM1_BUS_ID          1487
#define IDC_EDIT_FROM1_BUS_VOLT         1488
#define IDC_EDIT_FROM1_LOAD_VOLT        1489
#define IDC_COMBO_FROM2_CABLE_VOLT      1490
#define IDC_COMBO_FROM2_CABLE_TYPE      1491
#define IDC_COMBO2_FROM_CORE            1492
#define IDC_COMBO_FROM2_CORE            1492
#define IDC_COMBO_FROM2_CABLE_CORE      1492
#define IDC_EDIT_FROM2_SPEC             1493
#define IDC_EDIT_INPUT_KVA              1494
#define IDC_EDIT_TO_BUS_VOLT            1495
#define IDC_EDIT_TO_LOAD_VOLT           1496
#define IDC_EDIT_FROM1_LOAD_VOLT2       1496
#define IDC_RADIO_UPS_CAPACITY          1497
#define IDC_RADIO_DC_CAPACITY           1498
#define IDC_FPSPREAD_CONTROLCABLE_RESULT_VIEW 1499
#define IDC_EDIT_INPUT_BHP              1499
#define IDC_RADIO_LOAD_ALL_CONTROL_CABLE 1500
#define IDC_RADIO_ALL_CONTROL_CABLE     1500
#define IDC_EDIT_INPUT_BHP2             1500
#define IDC_EDIT_AC_RATING_BHP          1500
#define IDC_RADIO_UNSIZED_CONTROL_CABLE_ONLY 1501
#define IDC_FPSPREAD_USER_CABLE_RESULT_VIEW 1502
#define IDC_RADIO_DC_CAPACITY2          1502
#define ID_SCHEMATIC_CLEAR_BUTTON       1503
#define IDC_FPSPREAD_EXCEL_REPORT_FORMAT_VIEW 1504
#define IDC_FPSPREAD_EXCEL_REPORT_FORMAT_VIEW2 1505
#define IDC_FPSPREAD_EXCEL_REPORT_FORMAT_EDIT_VIEW 1505
#define IDC_GROUP_STATIC                1505
#define IDC_STATIC1                     1506
#define IDC_STATIC2                     1507
#define IDC_STATIC3                     1508
#define IDC_STATIC4                     1509
#define IDC_STATIC5                     1510
#define IDC_STD_CABLE_LENGTH_EDIT       1510
#define IDC_STATIC6                     1511
#define IDC_STD_CABLE_LENGTH_BUTTON     1511
#define IDC_STATIC7                     1512
#define IDC_CABLE_SPEC_LIST             1512
#define IDC_CABLE_SPEC_LIST_STATIC      1513
#define ID_CREATION_BUTTON              1514
#define IDC_CREATION_BUTTON             1514
#define IDC_CREATION_BUTTON2            1515
#define IDC_STATIC_AREA                 1515
#define IDC_BUTTON_CREATION             1516
#define IDC_FPSPREAD_DRUM_SCHEDULE_RESULT_VIEW 1517
#define IDC_DONT_HAVE_MCCB_VALUE_RADIO  1518
#define IDC_DONT_HAVE_MCCB_RADIO        1518
#define IDC_ALL_LOAD_RADIO              1519
#define IDC_COMBO_DATA_NAME             1520
#define IDC_FPSPREAD_LOAD_LIST_SLD      1521
#define IDC_BUTTON_EXPORT_LOAD          1522
#define IDC_CUSTOM1                     1523
#define IDC_STATIC_TR_CAPACITY          1524
#define IDC_STATIC_SEPERATOR            1525
#define IDC_STATIC_SELECT_LOAD_TYPE     1526
#define ID_WIZNEXT2                     12325
#define ID_VIEW_CUSTOMIZE               32770
#define ID_VIEW_TOOLBARS                32771
#define ID_SORT_MENU                    32789
#define ID_VIEW_WORKSPACE2              32792
#define ID_VIEW_USER_TOOLBAR1           32793
#define ID_VIEW_USER_TOOLBAR2           32794
#define ID_VIEW_USER_TOOLBAR3           32795
#define ID_VIEW_USER_TOOLBAR4           32796
#define ID_VIEW_USER_TOOLBAR5           32797
#define ID_VIEW_USER_TOOLBAR6           32798
#define ID_VIEW_USER_TOOLBAR7           32799
#define ID_VIEW_USER_TOOLBAR8           32800
#define ID_VIEW_USER_TOOLBAR9           32801
#define ID_VIEW_USER_TOOLBAR10          32802
#define ID_VIEW_WORKSPACE               32803
#define ID_VIEW_OUTPUT                  32804
#define ID_WINDOW_MANAGER               32825
#define ID_VIEW_APPLOOK_WIN_2000        32826
#define ID_VIEW_APPLOOK_OFF_XP          32827
#define ID_VIEW_APPLOOK_OFF_2003        32828
#define ID_VIEW_APPLOOK_WIN_XP          32829
#define ID_VIEW_APPLOOK_VS_2005         32830
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   32831
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  32832
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 32833
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   32834
#define ID_VIEW_APPLOOK_VS2008          32835
#define ID_CLASS_DEFINITION             32836
#define ID_CLASS_ADD_MEMEBER_FUNCTION   32837
#define ID_CLASS_ADD_MEMEBER_VARIABLE   32838
#define ID_CLASS_PROPERTIES             32839
#define ID_SORTING                      32852
#define ID_SORTING_SORTING              32853
#define ID_VIEW_CLASS                   32856
#define ID_TOOLS_MACRO                  32857
#define ID_SOLUTION_OPEN                32858
#define ID_RESOURCESUB_RESOURCESUB1     32859
#define ID_RESOURCESUB_RESOURCESUB2     32860
#define ID_LOAD_LIST                    32861
#define ID_FILTER_SORT_A_Z              32864
#define ID__SORTZTOA                    32865
#define ID_FILTER_SORT_Z_A              32866
#define ID_FILTER_SET                   32867
#define ID_FILTER_CLEAR                 32868
#define ID_SORTING_GROUPBYTYPE          32869
#define ID_Menu                         32869
#define ID_SORTING_SORTALF              32870
#define ID_CREATE_BUS_GROUP             32870
#define ID_SORTING_SORTBYTYPE           32871
#define ID_CREATE_BUG                   32871
#define ID_SORTING_SORTBYACCESS         32872
#define ID_CREATE_BUS                   32872
#define ID_CRETAE_BUS_GROUP             32873
#define ID_ITEM_SHOW                    32874
#define ID_ITEM_SHOWALL                 32876
#define ID_EXCEL_IMPORT                 32877
#define ID_EXPAND_ALL                   32878
#define ID_EXCEL_EXPORT                 32878
#define ID_SORTPROPERTIES               32879
#define ID_SORTINGPROP                  32879
#define ID_BUS                          32879
#define ID_PROPERTIES1                  32880
#define ID_BUSGROUP                     32880
#define ID_PROPERTIES2                  32881
#define ID_BUSGROUP_CREATEBUSGROUP      32881
#define ID_NEW_FOLDER                   32882
#define ID_PROPERTIES                   32883
#define ID_BUSCONTEXTMENU_COPYBUSGROUP  32883
#define IDS_WINDOWS_MANAGER             32884
#define ID_ITEM_DELETE                  32884
#define ID_ITEM_COPY                    32885
#define ID_ITEM_NEWLOAD                 32886
#define ID__COPYCTRL                    32887
#define ID_ITEM_MODIFY                  32888
#define ID_PASTECTRL                    32889
#define ID_COPYCTRL                     32890
#define ID_COPYBUS                      32891
#define ID_BUS_COPY                     32892
#define ID_BUSCONTEXTMENU_DELETE        32893
#define ID_DELETE_BUS_GROUP             32894
#define ID_BUS_DELETE                   32895
#define ID_ITEM_CREATE_POWER_CABLE_OF_SELECTED_LOAD 32896
#define ID_ITEM_ISSUE                   32897
#define ID_ITEM_VIEWLOGS                32898
#define ID_ITEM_CREATE_CONTROL_CABLE_OF_SELECTED_LOAD 32899
#define ID_VIEW_PROPERTIES              32900
#define ID_TOOLS_ASSIGNLOADTOBUS        32900
#define ID_Menu32901                    32901
#define ID_ITEM_SHOW_LIST               32902
#define ID_Menu32903                    32903
#define ID_ITEM_NEW                     32904
#define ID_Menu32905                    32905
#define ID_NEWPROJECT_DUMPELOADDB       32906
#define ID_VIEW_TOOLBARS32907           32907
#define ID_VIEW_OUTPUT_BAR              32908
#define ID_VIEW_ITEM_BAR                32909
#define ID_VIEW_PROPERTIES_BAR          32910
#define ID_TOOLS_PROJECT_SETTING        32911
#define ID_CALC_LOAD_SUMMARY            32912
#define ID_BUTTON32914                  32914
#define ID_TOOLS_EXCELCONVERSION        32915
#define ID_PRINT_LOAD_SUMMARY           32916
#define ID_CALC_CABLE_SIZE              32917
#define ID_Menu32918                    32918
#define ID_TOOLS_RELOAD_PYTHON          32919
#define ID_SHOWLOAD_SHOW_ALL_LIST       32920
#define ID_ADMIN_LIBRARY                32921
#define ID_PRINT_CABLE_SIZING           32922
#define ID_TOOLS_PROJECTSELECT          32923
#define ID_LIBRARY_CABLE_DATA           32924
#define ID_LIBRARY_CONDUIT_TABLE        32925
#define ID_CALC_LOAD_SIZE               32926
#define ID_PROJECT_VOLTAGE              32927
#define ID_CABLE_POWERCABLECREATION     32928
#define ID_CABLE_POWERCABLENAMINGRULE   32929
#define ID_LIBRARY_CABLESIZINGSETTING   32930
#define ID_LIBRARY_CABLE_SIZING_SETTING 32931
#define ID_CREATE_TRANSFORMER           32932
#define ID_COPY_TRANSFORMER             32933
#define ID_DELETE_TRANSFORMER           32934
#define ID_CREATE_LOAD                  32935
#define ID_CABLESIZINGRESULT_SHOWCABLESIZINGRESULT 32936
#define ID_CREATE_CABLE                 32937
#define ID_COPY_CABLE                   32938
#define ID_DELETE_CABLE                 32939
#define ID_DYNA_POPUP_MENU              32940
#define ID_CABLE_CONTROL_TYPE_CREATION  32941
#define ID_CABLE_SCHEMATIC_CREATION     32942
#define ID_CMDSET_RESERVED_3            32943
#define ID_CMDSET_RESERVED_4            32944
#define ID_CMDSET_RESERVED_5            32945
#define ID_CMDSET_RESERVED_6            32946
#define ID_CMDSET_RESERVED_7            32947
#define ID_CMDSET_RESERVED_8            32948
#define ID_CMDSET_RESERVED_9            32949
#define ID_CMDSET_RESERVED_10           32950
#define ID_CMDSET_RESERVED_11           32951
#define IDR_DYNAMIC_POPUP               32952
#define ID_CABLE_POWERCABLECREATION32953 32953
#define ID_CABLE_POWERCABLECREATION_SETTING 32954
#define ID_LOAD_VIRTUAL_LOAD_SUMMARY    32955
#define ID_Menu32956                    32956
#define ID_PROJECT_INFORMATION          32957
#define ID_LS_REFERENCE_SETTING         32958
#define ID_Menu32959                    32959
#define ID_Menu32960                    32960
#define LS_EXECUTION                    32961
#define ID_LV_POWER_CABLE_SIZING_TABLE_CREATION 32962
#define ID_POWER_CABLE_VERIFICATION_EXECUTION 32963
#define ID_DELETE_ITEM                  32964
#define ID_CONTROLCABLE                 32965
#define ID_Menu32965                    32966
#define ID_CONTROL_TYPE_CREATION        32967
#define ID_CONTROLCABLE_SCHEMATICTYPECREATION 32968
#define ID_SCHEMATIC_TYPE_CREATION      32969
#define ID_CONTROLTYPECREATION_INSERT   32970
#define ID_CONTROLTYPECREATION_DELETE   32971
#define ID_CONTROLCABLE_CONTROLCABLE    32972
#define ID_CONTROLCABLE_CREATION_SETTING 32973
#define ID_SD                           32974
#define ID_MCCB_SIZE_SETTING            32975
#define ID_USER_CABLE_IMPORT            32976
#define ID_CABLE_SCHEDULE_SETTING       32977
#define ID_Menu32978                    32978
#define ID_Menu32979                    32979
#define ID_Menu32980                    32980
#define ID_Menu32981                    32981
#define ID_CONTROL_CABLE_SPEC_CREATION  32982
#define ID_SCHEMATIC_TYPE_ASSIGN_TO_LOAD 32983
#define ID_CONTROL_CABLE_CREATION       32984
#define ID_CABLE_ROUTE_CREATION         32985
#define ID_CABLE_ROUTE_ASSIGN_TO_LOAD   32986
#define ID_CABLE_TRAY_FILL_RATE_EXECUTION 32987
#define ID_CABLE_SCHEDULE_CREATION      32988
#define ID_CABLE_BM_SUMMARY             32989
#define ID_VIEW_CAPTIONBAR              32990
#define ID_VIEW_CAPTION_BAR             32991
#define ID_OFFICE2007                   32992
#define ID_OFFICE2008                   32993
#define ID_SAVE_CABLE_SIZE_TO_REVISION  32999
#define ID_ADMIN_CREATE_PROJECT         33000
#define ID_SAVE_LOAD_SUMMARY_TO_REVISION 33001
#define ID_ADMIN_DUMP_DB                33002
#define ID_SAVE_POWER_CABLE_TO_REVISION 33003
#define ID_SAVE_PRODUCT_TO_REVISION     33004
#define ID_VIEW_REVISION                33005
#define ID_CABLE_R1                     33006
#define ID_CABLE_ROUTE_TYPE_CREATION    33007
#define ID_CABLE_ROUTE_GROUND_CREATION  33008
#define ID_CABLE_ROUTE_ASSIGNTOLOAD     33009
#define ID_CABLE_TRAY_FILLRATE_EXECUTION 33010
#define ID_CABLESIZINGRESULT_VIEWREVISION 33011
#define ID_CABLE_ROUTE_GROUP_CREATION   33012
#define ID_CAPACITORCONTEXTMENU_NEWCAPACITOR 33013
#define ID_CAPACITORCONTEXTMENU_COPY    33014
#define ID_CAPACITORCONTEXTMENU_DELETE  33015
#define ID_GENERATORCONTEXTMENU_NEWGENERATOR 33016
#define ID_GENERATORCONTEXTMENU_COPY    33017
#define ID_GENERATORCONTEXTMENU_DELETE  33018
#define ID_BUS_PRINTSETUP               33019
#define ID_BUS_PRINT                    33020
#define ID_Menu33021                    33021
#define ID_UPSDCCONTEXTMENU_NEWUPSDC    33022
#define ID_UPSDCCONTEXTMENU_COPY        33023
#define ID_UPSDCCONTEXTMENU_DELETE      33024
#define ID_SCHEMATICMENU_DELETE         33025
#define ID_SCHEMATICMENU_MODIFY         33026
#define ID_CONTROLTYPEMENU_DELETE       33027
#define ID_USER_NEWCABLE                33029
#define ID_USER_DELETECABLE             33030
#define ID_TOOLS_MAKE_EXCEL_REPORT_FORMAT 33031
#define ID_TOOLS_MAKEEXCEPREPORTFORMAT  33032
#define ID_USERCABLE_CABLESCHEDULESETTING 33033
#define ID_USER_CABLESCHEDULESETTING    33034
#define ID_USER_CABLE_SCHEDULE_SETTING  33035
#define ID_DELETE_ALL_CABLE             33036
#define ID_TOOLS_TEMPLATE_MAPPING       33037
#define ID_REVDELETE_REVDELETE          33038
#define ID_REV_ITEM_DELETE              33039
#define ID_CABLEROUTE_DELETE            33040
#define ID_CABLE_ROUTE_DELETE           33041
#define ID_POWERCABLE_POWERCABLEERROR   33042
#define ID_POWERCABLE_ERROR_LOG         33043
#define ID_CONTROLCABLE_CO              33044
#define ID_CONTROLCABLE_ERROR_LOG       33045
#define ID_LOAD_SUMMARY_ERROR_LOG       33046
#define ID_EXCEL_IMPORT_ERROR_LOG       33047
#define ID_DRUM_SCHEDULE_CREATION       33048
#define ID_CONTROL_CABLE_VERIFICATION   33049
#define ID_CABLE_DATA_DELETE            33050
#define ID_BUS_DIAGRAM_OPEN             33051
#define ID_ACCELERATOR_HELP             33054
#define IDR_DRAW_TOOLBAR                33056
#define ID_TOOL_BUS_TO_BUS              33057
#define ID_TOOL_CREATE_BUS_TO_BUS_RELATION 33059
#define ID_TOOL_SAVE_BUS_TO_BUS_RELATION 33060

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        420
#define _APS_NEXT_COMMAND_VALUE         33062
#define _APS_NEXT_CONTROL_VALUE         1527
#define _APS_NEXT_SYMED_VALUE           119
#endif
#endif
